apiVersion: v1
kind: Service
metadata:
  name: bbx-nginx
  namespace: axiom-apps
  labels:
    app.kubernetes.io/name: bbx-nginx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bbx-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
