apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: axiom-apps
  labels:
    app.kubernetes.io/name: demo-web
    app.kubernetes.io/managed-by: axiom-idp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-web
        app.kubernetes.io/managed-by: axiom-idp
    spec:
      automountServiceAccountToken: false
      containers:
        - name: demo-web
          image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
